name: CI
on:
  - push
  - pull_request

jobs:

  test:
    strategy:
      matrix:
        include:
          - node: 10
          - node: 12
          - node: 14
          - node: 16
          - node: 18
          - node: 20
          - node: 24

    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - run: npm install

      - run: npm test